project:
  type: website

website:
  title: "HelenaJamborWrites"
  description: "This is Helena Jambor's personal blog and website. I write about life sciences and data visualization, most of the time merged as biovis. I am mostly interested in visual communication of scientific data." 
  navbar:
    right:
      - about.qmd
      - icon: github
        text: Github
        href: https://github.com/helenajambor        
      - icon: twitter
        text: Twitter
        href: https://twitter.com/helenajambor
      - icon: linkedin
        text: LinkedIn
        href: https://linkedin.com//in/helena-klara-jambor-b35b507b
        
format:
  html:
    theme: cosmo
    css: styles.css



