project:
  type: website
  
website:
  title: "HelenaJamborWrites"
  description: "Blog about data visualization and visual communication of scientific data" 
  site-url: https://helenajamborwrites.netlify.app/
  navbar:
    right:
      - about.qmd
      - text: "Science"
        file: science.qmd
      - text: "Talks & courses"
        file: talks.qmd
      - doodles.qmd
      - icon: github
        text: Github
        href: https://github.com/helenajambor        
      - icon: mastodon
        text: Mastodon
        href: https://vis.social/@helenajambor        
      - text: Twitter
        href: https://twitter.com/helenajambor
      - icon: linkedin
        text: LinkedIn
        href: https://linkedin.com//in/helena-klara-jambor-b35b507b
      - icon: rss
        href: index.xml
  
format:
  html:
    theme: lux
    css: styles.css



