---
title: ""
---
I give a lot of scientific talks and workshops on Data Communication, Biomedical Visualization, and at times RNA biology. Rarely also on the history of visualizations in biology!

### Scientific talks
##### 2022
<p><strong>FEBS</strong> Danube Conference Epigenetics, invited talk, Budapest</p>
<p> <strong>HT</strong> Human Technopole, Mailand, invited talk</p>
<p> <strong>ISMB</strong>, Madison Wisconsin, Conference chair BioVis COSI</p>
<p> Else-Kr&ouml;ner Clinician Scientists Programm Retreat, invited talk</p>
<p> European Light Microscopy Initiative, Turku Finnland, invited talk</p>
<p> Sharing Knowledge Talk, <strong>University of T&uuml;bingen Excellence Programme</strong>, invited talk</p>
<p> Lipid Metabolism Summer School, Dresden, invited talk</p>
<p> 19th Annual Advanced Imaging Methods, Berkeley, invited talk</p>
##### 2021
<p><strong>FENS</strong> (Federation of European Neuroscience Society) Webinar &ldquo;Figures for Scientific Publications&rdquo;</p>
<p> <strong>ISMB </strong>BioVis invited high-light talk &ldquo;Image quality in publications&rdquo;</p>
<p> <strong>FEBS</strong> Danube Conference on Epigenetics, invited talk &ldquo;Data Visualization&rdquo;</p>
<p> DPG, Young Physiologists Symposium, &ldquo;Image and Data Visualization&rdquo;</p>
<p> HAW Hochschule f&uuml;r Angewandte Wissenschaften, Hamburg, lecture &ldquo;Data Visualization&rdquo; for the call <em>Chair in Data Visualization</em></p>
<p> Hochschule Ingolstadt, lectures &ldquo;NGS Sequencing of SARS-CoV-2&rdquo; and &ldquo;Data Visualization&rdquo; for the call <em>Chair in Medical Informatics</em></p>
<p> Hochschule Fulda, lectures &ldquo;Feedback mechanisms&rdquo; and &ldquo;Data Visualization&rdquo; for the call <em>Chair in Visual Analytics</em></p>
<p> EKFZ <strong>Digital Health Spring School</strong> &ldquo;Medical Data Visualization&rdquo;</p>
##### 2020
<p><strong>Woodstock of Biology, Tel-Aviv</strong>, &ldquo;My pretty little big data visualized&rdquo;</p>
<p> <strong>S&auml;chsische Landes&auml;rztekammer</strong>, Physician training in digital medicine/visualization of medical data</p>
<p> Hochschule Coburg, lectures &ldquo;Microarrays&rdquo;, &ldquo;Data Visualization&rdquo; for the call chair in bioinformatics.</p>
<p> German BioImaging Society, lecture for society seminar series &ldquo;Image quality in publications&rdquo; <a href="https://youtu.be/NfXSddDOyt8"><strong>https://youtu.be/NfXSddDOyt8</strong></a></p>
<p> <strong>FH Graub&uuml;nden, CH, </strong>guest lecture at Swiss institute for Information science in the context of the appointment for chair &ldquo;Data visualization&rdquo;, list position 2.</p>
##### 2019
<p><strong>Hochschule Beuth</strong> Berlin, guest lecture for Prof. Simone Reber &ldquo;Introduction to DataViz bioinformatics&rdquo;</p>
<p> <strong>Max-Planck-Institut Zellbiologie</strong> &ldquo;Data Visualization &ndash; poster design&rdquo;</p>
<p> <strong>BIMSB</strong> Berlin, laboratory of Prof. Uwe Ohler &ldquo;Scientific data visualization&rdquo;</p>
##### 2018
<p><strong>TU Dresden</strong>, &ldquo;Introduction to scientific data visualization&rdquo; for PhD students from all disciplines</p>
<p> <strong>Faculty of Computer science, Magdeburg</strong>, &ldquo;Visualization of life science data&rdquo;, invitation by Prof. Holger Theisel</p>
<p> <strong>IMG Prague</strong>, PhD students conference, &ldquo;Introduction to visual communication&rdquo;</p>
<p> <strong>Dresden Biopolis</strong> PhD student conference &ldquo;Poster and figure design&rdquo;.</p>
<p> <strong>Dresden DIGS-BB</strong> ask the Expert session &ldquo;Visual communication&rdquo;.</p>
<p> <strong>DGZ conference</strong>, Berlin &ldquo;DataViz for life sciences&rdquo;.</p>
##### 2008-2017
<p>Predoc course DIPP, &ldquo;Life science figure design&rdquo;.</p>
<p> SignGene Winter school, <strong>Elat Israel</strong> (invited Talk).</p>
<p> DFG FOR233 meeting, <strong>Heidelberg</strong>.</p>
<p><strong>TedEx talk</strong>, Frankfurt, &ldquo;History of Life Science Images&rdquo;.</p>
<p> Wissenschaftskolleg Berlin, &ldquo;RNAs in Space and Time - How Ribonucleic Acid Determines Cell Organization&rdquo;.</p>
<p> Workshop on &ldquo;Life Science Figure Design&rdquo;: Max-Planck Institute Dresden, University of Gothenburg, IMP/IMBA Wien, HU Berlin.</p>
<p> <strong>MDC Berlin</strong> (Invited by Prof. Rajewski).</p>
<p>BIOTEC, Dresden (Invited by Prof. Stewart).</p>
<p> EMBO RNA Localization and local translation, <strong>Crete</strong>.</p>
<p> Berlin Summer Meeting, <strong>Berlin</strong> (invited Talk).</p>
<p>University of Heidelberg (Invited by Prof. Wittbrodt).</p>
<p> University of <strong>Regensburg</strong> (Invited by Dr. Medenbach).</p>
<p><strong>New York University</strong> Langone Medical Center (Invited by Prof. Lehmann).</p>
<p> <strong>Whitehead Institute</strong>, MIT, Cambridge (Invited by Prof. Orr-Weaver).</p>
<p> EMBL, Heidelberg (Invited by Anne Ephrussi).</p>
<p> Max-Planck Institute in Dresden, Institute seminar.</p>
<p>Max-Planck Institute T&uuml;bingen (Invited by Dr. Bono).</p>
<p>European Drosophila Research Conference, Berlin Summer Meeting.</p>
<p>Max Planck Institute fo. Neurobiology (Invited by Dr. Frank Bradke),</p>
<p> University of Cambridge, UK (Invited by Dr. Jordan Raff),</p>
<p> KU Leuven. (Invited by Dr. Bassem Hassan).</p>
<p>DGZ Young Scientist Meeting.</p>

### DataViz Workshops
CNC - Center for Neuroscience and Cell Biology, BEB Doctoral Program course, workshop Visual communication of biomedical data. 
Graduate School ESGC, Erasmus, Faculty of Environment and Natural Resources, University of Freiburg, 3-day virtual course. 
International Institute of Molecular and Cell Biology, MOSaic initiative, Warszawa, Poland, 4-day virtual course for advanced scientists.
TU Dresden, Graduate Academy, PhD, 2 courses
Charite Berlin, Quantum Futur Academy, undergraduate students
Junge Physiologen, annual meeting, physicians and medical scientsits
EKFZ Spring School, undergraduates in medicine and engineering
TU Dresden, Graduate Academy, PhD, 2 courses
Helmholtz Rossendorf, postdocs 
Sächsische Ärztekammer, resident physicians 
BISMB/MDC Ohler lab, scientists
Iain Patten, online course
MPI Dortmund, PhD students
TU Dresden, Graduate Academy, PhD, 2 courses
MPI-CBG, postdoc retreat
Max Planck Society, scientists and science communicators
Hemlhotz MUC/Henry/ lab
HU Berlin, IRI graduate School
Uni. Regensburg, PhD program
TU Dresden, Graduate Academy, PhD, 2 courses
MPI-AGE, PhD students
Center for regenerative therapies, postdocs
Dresnden International Graduate School, PhD students
IMG Prague, PhD students
MPI-CBG, postdocs
IRI, HU Berlin, PhD
Helmholtz Müchen, PhD, 4 courses
DFG Forschergruppe RNA Localization, training for members
Univ. Frankfurt, Dept Biochemie
EMBO Young Investigator Program Annual meeting
VBCF (IMBA/IMP) Vienna
Univ. Götheburg, Sweden, department retreat
Pharmacy, University Hospital Dresden

### Meetup series
During the pandemic I founded the DataViz helpdesk to teach visualization to scientists myself, later on I also had guests for tutorials (see [DataViz academy on youtube](https://www.youtube.com/playlist?list=PL5kIQRQ6TU8Ifu_5h2iipUmIKCqhs50zx)), this kicked off the 
[BioVis meetup series](http://biovis.net/2022/meetup/).

### Undergraduate teaching 
I regularly teach Bachelor and Master students at Berlin Hochschule für Technik (Bioinformatics, Data Visualization) and at the TU Dresden give courses for medical and biology students in data science and visualization. 

